// This file is @generated by prost-build.
/// Unique identifier for a node in the graph.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NodeId {
    #[prost(uint64, tag = "1")]
    pub id: u64,
}
/// Unique identifier for an edge in the graph.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EdgeId {
    #[prost(uint64, tag = "1")]
    pub id: u64,
}
/// Hybrid Logical Clock timestamp.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HlcTimestamp {
    #[prost(uint64, tag = "1")]
    pub wall_time: u64,
    #[prost(uint32, tag = "2")]
    pub logical: u32,
}
/// A typed property value (oneof for all supported types).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PropertyValue {
    #[prost(oneof = "property_value::Value", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9")]
    pub value: ::core::option::Option<property_value::Value>,
}
/// Nested message and enum types in `PropertyValue`.
pub mod property_value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(int64, tag = "1")]
        IntValue(i64),
        #[prost(double, tag = "2")]
        FloatValue(f64),
        #[prost(string, tag = "3")]
        StringValue(::prost::alloc::string::String),
        #[prost(bool, tag = "4")]
        BoolValue(bool),
        #[prost(bytes, tag = "5")]
        BytesValue(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag = "6")]
        TimestampValue(super::HlcTimestamp),
        #[prost(message, tag = "7")]
        VectorValue(super::Vector),
        #[prost(message, tag = "8")]
        ListValue(super::PropertyList),
        #[prost(message, tag = "9")]
        MapValue(super::PropertyMap),
    }
}
/// A dense float vector for vector search.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Vector {
    #[prost(float, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<f32>,
}
/// A list of property values (homogeneous arrays).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PropertyList {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<PropertyValue>,
}
/// A map of string keys to property values.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PropertyMap {
    #[prost(map = "string, message", tag = "1")]
    pub entries: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        PropertyValue,
    >,
}
/// Cursor-based pagination request parameters.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaginationRequest {
    /// Maximum number of results to return.
    #[prost(int32, tag = "1")]
    pub page_size: i32,
    /// Opaque cursor from a previous response.
    #[prost(string, tag = "2")]
    pub page_token: ::prost::alloc::string::String,
}
/// Cursor-based pagination response metadata.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaginationResponse {
    /// Opaque cursor for the next page. Empty if no more results.
    #[prost(string, tag = "1")]
    pub next_page_token: ::prost::alloc::string::String,
    /// Total count of matching results (if available, -1 if unknown).
    #[prost(int64, tag = "2")]
    pub total_count: i64,
}
/// Sort specification for query results.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SortOption {
    #[prost(string, tag = "1")]
    pub field: ::prost::alloc::string::String,
    #[prost(enumeration = "SortDirection", tag = "2")]
    pub direction: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SortDirection {
    Unspecified = 0,
    Asc = 1,
    Desc = 2,
}
impl SortDirection {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SORT_DIRECTION_UNSPECIFIED",
            Self::Asc => "SORT_DIRECTION_ASC",
            Self::Desc => "SORT_DIRECTION_DESC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SORT_DIRECTION_UNSPECIFIED" => Some(Self::Unspecified),
            "SORT_DIRECTION_ASC" => Some(Self::Asc),
            "SORT_DIRECTION_DESC" => Some(Self::Desc),
            _ => None,
        }
    }
}
