// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetClusterStatusRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClusterStatus {
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<ClusterNode>,
    /// Node ID of the current Raft leader. Empty string if no leader elected.
    #[prost(string, tag = "2")]
    pub leader_id: ::prost::alloc::string::String,
    /// Current Raft term. Monotonically increasing across leader elections.
    #[prost(uint64, tag = "3")]
    pub raft_term: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClusterNode {
    /// Numeric node ID as string (matches --id flag in CLI).
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    /// gRPC address of the node (host:port). May be empty for follower self-report.
    #[prost(string, tag = "2")]
    pub address: ::prost::alloc::string::String,
    #[prost(enumeration = "NodeRole", tag = "3")]
    pub role: i32,
    #[prost(enumeration = "NodeState", tag = "4")]
    pub state: i32,
    /// Number of Raft log entries this node is behind the leader.
    /// Zero for the leader itself. Used for read routing staleness checks.
    #[prost(uint64, tag = "5")]
    pub lag_entries: u64,
}
/// Request to initiate a cluster join for a new node.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JoinNodeRequest {
    /// Numeric node ID to assign. Must be unique across the cluster.
    /// The target node must already be running and listening on address.
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
    /// gRPC address of the new node in "host:port" format.
    /// The leader will replicate log entries to this address.
    #[prost(string, tag = "2")]
    pub address: ::prost::alloc::string::String,
    /// If true, the new node has pre-seeded data from an offline snapshot backup.
    /// Used as a hint: the leader logs "Tier 3 skip expected" in the initial
    /// progress event. Actual Tier-3 skip behavior runs on the joining node side.
    #[prost(bool, tag = "3")]
    pub pre_seeded: bool,
}
/// Response to JoinNode — the join lifecycle has been initiated.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JoinNodeResponse {
    /// Numeric node ID of the joining node (echoed from request).
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
    /// Human-readable status. Currently always "JOIN_INITIATED".
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
}
/// Request to subscribe to join progress events.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JoinProgressRequest {
    /// Node ID whose join lifecycle to observe (must match a JoinNode call).
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
}
/// A single join progress event, emitted during the join lifecycle.
///
/// The stream emits events at each phase transition and every ~500ms lag poll.
/// The stream closes after COMPLETE or FAILED is emitted.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JoinStatus {
    /// Node ID of the joining node.
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
    /// Current join phase.
    #[prost(enumeration = "JoinPhase", tag = "2")]
    pub phase: i32,
    /// Number of Raft log entries behind the leader. Zero when unknown or complete.
    #[prost(uint64, tag = "3")]
    pub lag_entries: u64,
    /// Estimated completion percentage (0–100). 100 means complete.
    #[prost(uint32, tag = "4")]
    pub percent: u32,
    /// Human-readable status message for display in CLI --follow output.
    #[prost(string, tag = "5")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddNodeRequest {
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveNodeRequest {
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveNodeResponse {}
/// Request to gracefully decommission a node from the cluster.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DecommissionNodeRequest {
    /// Numeric node ID to decommission. Must be in the current voter set.
    /// The node will be removed from Raft membership after quorum and drain checks pass.
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
    /// If true, the decommissioned node's data should be wiped after removal.
    /// In CE, this is advisory — operator must delete data on node_id manually.
    /// The response will set operator_cleanup_required=true as a reminder.
    /// In EE, storage is freed progressively as each shard move completes (Phase 1).
    #[prost(bool, tag = "2")]
    pub pruning: bool,
    /// Emergency decommission: skip quorum gate and drain, force membership remove
    /// even if node_id is unreachable. May cause permanent data loss if node_id
    /// held the only copy of any shard.
    /// Requires skip_confirmation=true to guard against accidental invocation.
    #[prost(bool, tag = "3")]
    pub force: bool,
    /// Must be set to true when force=true to confirm awareness of potential data loss.
    /// Prevents accidental use of --force without understanding the consequences.
    /// Ignored when force=false.
    #[prost(bool, tag = "4")]
    pub skip_confirmation: bool,
}
/// Response from DecommissionNode.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DecommissionNodeResponse {
    /// Numeric node ID that was decommissioned.
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
    /// Human-readable status message describing the phases executed.
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// Set when pruning=true was requested.
    /// In CE, operator must manually delete data on the decommissioned node.
    /// In EE, storage is freed automatically during Phase 1 shard moves.
    #[prost(bool, tag = "3")]
    pub operator_cleanup_required: bool,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NodeRole {
    Unspecified = 0,
    /// Leader — handles all writes and coordinates replication.
    Leader = 1,
    /// Voting follower — participates in elections and quorum.
    Follower = 2,
    /// Non-voting learner — receives replication but does not vote.
    Learner = 3,
}
impl NodeRole {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "NODE_ROLE_UNSPECIFIED",
            Self::Leader => "NODE_ROLE_LEADER",
            Self::Follower => "NODE_ROLE_FOLLOWER",
            Self::Learner => "NODE_ROLE_LEARNER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NODE_ROLE_UNSPECIFIED" => Some(Self::Unspecified),
            "NODE_ROLE_LEADER" => Some(Self::Leader),
            "NODE_ROLE_FOLLOWER" => Some(Self::Follower),
            "NODE_ROLE_LEARNER" => Some(Self::Learner),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NodeState {
    Unspecified = 0,
    /// Healthy — lag within acceptable threshold.
    Healthy = 1,
    /// Degraded — lag exceeds threshold or heartbeat delayed.
    Degraded = 2,
    /// Down — not reachable or no heartbeat received.
    Down = 3,
}
impl NodeState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "NODE_STATE_UNSPECIFIED",
            Self::Healthy => "NODE_STATE_HEALTHY",
            Self::Degraded => "NODE_STATE_DEGRADED",
            Self::Down => "NODE_STATE_DOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NODE_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "NODE_STATE_HEALTHY" => Some(Self::Healthy),
            "NODE_STATE_DEGRADED" => Some(Self::Degraded),
            "NODE_STATE_DOWN" => Some(Self::Down),
            _ => None,
        }
    }
}
/// Phase progression for a node join lifecycle.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum JoinPhase {
    Unspecified = 0,
    /// Node added as Learner — receiving log replication, replication lag closing.
    Learner = 1,
    /// Lag below threshold (1000 entries) — promoting to Voter imminently.
    ReadyCheck = 2,
    /// change_membership in progress — node becoming a Voter.
    Promoting = 3,
    /// Node is now a Voter. Join complete. Stream closes after this event.
    Complete = 4,
    /// Join failed (see message). Stream closes after this event.
    Failed = 5,
}
impl JoinPhase {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "JOIN_PHASE_UNSPECIFIED",
            Self::Learner => "JOIN_PHASE_LEARNER",
            Self::ReadyCheck => "JOIN_PHASE_READY_CHECK",
            Self::Promoting => "JOIN_PHASE_PROMOTING",
            Self::Complete => "JOIN_PHASE_COMPLETE",
            Self::Failed => "JOIN_PHASE_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "JOIN_PHASE_UNSPECIFIED" => Some(Self::Unspecified),
            "JOIN_PHASE_LEARNER" => Some(Self::Learner),
            "JOIN_PHASE_READY_CHECK" => Some(Self::ReadyCheck),
            "JOIN_PHASE_PROMOTING" => Some(Self::Promoting),
            "JOIN_PHASE_COMPLETE" => Some(Self::Complete),
            "JOIN_PHASE_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod cluster_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Cluster management operations.
    #[derive(Debug, Clone)]
    pub struct ClusterServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ClusterServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ClusterServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ClusterServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ClusterServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Get the current cluster status.
        pub async fn get_cluster_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetClusterStatusRequest>,
        ) -> std::result::Result<tonic::Response<super::ClusterStatus>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/coordinode.v1.admin.ClusterService/GetClusterStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "coordinode.v1.admin.ClusterService",
                        "GetClusterStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Initiate a cluster join lifecycle for a new node.
        ///
        /// Adds the target node as a Learner (non-voting) and starts a background
        /// monitor that promotes it to Voter once replication lag drops below
        /// READINESS_LAG_THRESHOLD (1000 entries). Must be called on the leader.
        ///
        /// Returns immediately after the Learner is added. Use JoinProgress to
        /// stream phase events until COMPLETE or FAILED.
        pub async fn join_node(
            &mut self,
            request: impl tonic::IntoRequest<super::JoinNodeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::JoinNodeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/coordinode.v1.admin.ClusterService/JoinNode",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("coordinode.v1.admin.ClusterService", "JoinNode"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Stream join progress events for a node join in progress.
        ///
        /// Returns a server-streaming response of JoinStatus messages until
        /// the join reaches COMPLETE or FAILED phase. The stream closes automatically
        /// after either terminal phase is emitted.
        ///
        /// Returns NOT_FOUND if JoinNode was not called for this node_id or if
        /// the join has already completed.
        pub async fn join_progress(
            &mut self,
            request: impl tonic::IntoRequest<super::JoinProgressRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::JoinStatus>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/coordinode.v1.admin.ClusterService/JoinProgress",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("coordinode.v1.admin.ClusterService", "JoinProgress"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Add a node to the cluster (low-level, auto-assigned ID).
        ///
        /// Deprecated: use JoinNode with an explicit node_id and address instead.
        /// This RPC is retained for API compatibility but returns UNIMPLEMENTED.
        pub async fn add_node(
            &mut self,
            request: impl tonic::IntoRequest<super::AddNodeRequest>,
        ) -> std::result::Result<tonic::Response<super::ClusterNode>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/coordinode.v1.admin.ClusterService/AddNode",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("coordinode.v1.admin.ClusterService", "AddNode"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Remove a node from the cluster.
        pub async fn remove_node(
            &mut self,
            request: impl tonic::IntoRequest<super::RemoveNodeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RemoveNodeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/coordinode.v1.admin.ClusterService/RemoveNode",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("coordinode.v1.admin.ClusterService", "RemoveNode"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Gracefully decommission a node from the cluster.
        ///
        /// Implements the Phase 0-2 decommission protocol:
        /// Phase 0: Quorum gate — verify removing node_id still leaves ≥ 2 voters.
        /// Aborts with FAILED_PRECONDITION if quorum would be lost.
        /// Phase 1: Leadership transfer — if node_id is the current Raft leader,
        /// leadership is transferred to a peer before removal.
        /// For self-decommission (leader removing itself), the request is
        /// internally forwarded to the new leader after transfer.
        /// Phase 2: Membership remove — change_membership(remove: node_id).
        /// Node stops receiving log replication and is removed from quorum.
        ///
        /// CE behaviour: single Raft group, all nodes hold full data. Pruning (Phase 3)
        /// is advisory — operator must delete data on the decommissioned node manually.
        ///
        /// Must be called on the current Raft leader, or on the node being decommissioned
        /// when that node is the leader (self-decommission path).
        /// Use force=true for emergency removal of an unreachable node (may lose data).
        pub async fn decommission_node(
            &mut self,
            request: impl tonic::IntoRequest<super::DecommissionNodeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DecommissionNodeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/coordinode.v1.admin.ClusterService/DecommissionNode",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "coordinode.v1.admin.ClusterService",
                        "DecommissionNode",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
