// This file is @generated by prost-build.
/// One operation sent by the client on the session stream.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientFrame {
    /// Client-assigned, session-scoped correlation id. Every ServerFrame produced
    /// for this operation carries the same request_id, so a client demultiplexes
    /// concurrent responses and cursor chunks that arrive out of order. The client
    /// is responsible for keeping request_ids unique within a live session.
    #[prost(uint64, tag = "1")]
    pub request_id: u64,
    /// The operation. Exactly one is set.
    #[prost(oneof = "client_frame::Op", tags = "2, 3, 4, 5, 6, 7")]
    pub op: ::core::option::Option<client_frame::Op>,
}
/// Nested message and enum types in `ClientFrame`.
pub mod client_frame {
    /// The operation. Exactly one is set.
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Op {
        /// Run a query statement (autonomous or inside a transaction).
        #[prost(message, tag = "2")]
        Execute(super::Execute),
        /// Open an interactive transaction; the server replies with a Begun(txid).
        #[prost(message, tag = "3")]
        Begin(super::Begin),
        /// Commit an interactive transaction by its txid.
        #[prost(message, tag = "4")]
        Commit(super::Commit),
        /// Roll back an interactive transaction by its txid.
        #[prost(message, tag = "5")]
        Rollback(super::Rollback),
        /// Abort an in-flight request and close its cursor.
        #[prost(message, tag = "6")]
        Cancel(super::Cancel),
        /// Read, and optionally change, this connection's settings. Answered with
        /// a ConnectionStatus carrying the settings now in effect.
        #[prost(message, tag = "7")]
        Configure(super::Configure),
    }
}
/// Read, and optionally change, the settings this connection applies to
/// statements that do not carry their own.
///
/// Every field is optional: one that is absent is left as it is, so a client
/// changes one setting without restating the others, and a Configure with none
/// set is simply a request to report the current status. The server answers
/// with a ConnectionStatus whose settings are the ones now in effect, which is
/// how a client confirms a change actually took rather than assuming it did.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Configure {
    /// Default read concern for statements that carry none.
    #[prost(message, optional, tag = "1")]
    pub read_concern: ::core::option::Option<super::replication::ReadConcern>,
    /// Default write concern for statements that carry none.
    #[prost(message, optional, tag = "2")]
    pub write_concern: ::core::option::Option<super::replication::WriteConcern>,
    /// Default read preference for statements that carry none.
    #[prost(enumeration = "super::replication::ReadPreference", optional, tag = "3")]
    pub read_preference: ::core::option::Option<i32>,
    /// Default reorder-buffer drain timeout, in milliseconds, for transactions
    /// opened with ORDERING_ORDERED and no explicit drain_timeout_ms.
    #[prost(uint32, optional, tag = "4")]
    pub drain_timeout_ms: ::core::option::Option<u32>,
}
/// Execute one query statement.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Execute {
    /// Query text in the session's dialect (Cypher today; SQL once the SQL
    /// frontend lands). The server selects a query frontend per session or per
    /// statement and never inspects the syntax above that frontend.
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    /// Named query parameters bound at execution time. Same shape as the unary
    /// ExecuteCypherRequest parameters.
    #[prost(map = "string, message", tag = "2")]
    pub parameters: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        super::common::PropertyValue,
    >,
    /// Interactive transaction handle from a prior Begun. Zero means the statement
    /// is autonomous (implicit begin + commit). Non-zero runs the statement inside
    /// that transaction: it reads the transaction's pinned snapshot and its writes
    /// buffer until Commit.
    #[prost(uint64, tag = "3")]
    pub txid: u64,
    /// Per-transaction ordering nonce, used only when the transaction was opened
    /// with ORDERING_ORDERED. The server applies the transaction's statements in
    /// ascending nonce order regardless of wire-arrival order. Ignored for
    /// autonomous statements and for ORDERING_UNORDERED transactions.
    #[prost(uint64, tag = "4")]
    pub nonce: u64,
}
/// Open an interactive transaction.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Begin {
    /// Statement ordering policy for the transaction.
    #[prost(enumeration = "Ordering", tag = "1")]
    pub ordering: i32,
    /// How long (milliseconds) the server's reorder buffer waits for a missing
    /// nonce before aborting the transaction, in ORDERING_ORDERED mode. Zero uses
    /// the per-session default. Distinct from the idle-reap timeout that closes an
    /// untouched transaction.
    #[prost(uint32, tag = "2")]
    pub drain_timeout_ms: u32,
}
/// Commit an interactive transaction.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Commit {
    /// Transaction handle from a prior Begun.
    #[prost(uint64, tag = "1")]
    pub txid: u64,
    /// Expected final nonce of the transaction's statement chain, in
    /// ORDERING_ORDERED mode, so the server can detect a complete chain before it
    /// commits. Zero when unset (UNORDERED transactions, or callers that do not
    /// pipeline ahead of the commit).
    #[prost(uint64, tag = "2")]
    pub last_nonce: u64,
}
/// Roll back an interactive transaction, discarding all buffered writes.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Rollback {
    /// Transaction handle from a prior Begun.
    #[prost(uint64, tag = "1")]
    pub txid: u64,
}
/// Abort an in-flight request and close its cursor.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Cancel {
    /// request_id of the in-flight request to abort.
    #[prost(uint64, tag = "1")]
    pub target_request_id: u64,
}
/// One result event sent by the server on the session stream.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerFrame {
    /// request_id of the ClientFrame this event answers.
    #[prost(uint64, tag = "1")]
    pub request_id: u64,
    /// The event. Exactly one is set.
    #[prost(oneof = "server_frame::Event", tags = "2, 3, 4, 5, 6, 7, 8")]
    pub event: ::core::option::Option<server_frame::Event>,
}
/// Nested message and enum types in `ServerFrame`.
pub mod server_frame {
    /// The event. Exactly one is set.
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        /// Acknowledges Begin and returns the allocated transaction handle.
        #[prost(message, tag = "2")]
        Begun(super::Begun),
        /// Opens a cursor for a query, carrying the column header.
        #[prost(message, tag = "3")]
        CursorOpen(super::CursorOpen),
        /// A batch of result rows for an open cursor; many may arrive per request.
        #[prost(message, tag = "4")]
        Rows(super::RowBatch),
        /// Closes a cursor, carrying final query statistics.
        #[prost(message, tag = "5")]
        CursorEnd(super::CursorEnd),
        /// Acknowledges Commit, carrying the causal applied-index token.
        #[prost(message, tag = "6")]
        Committed(super::Committed),
        /// Reports an error for the request; terminates its cursor.
        #[prost(message, tag = "7")]
        Error(super::SessionError),
        /// The state of this connection: whether it can serve writes, what it can
        /// see of the cluster, and the settings in effect. Sent in answer to a
        /// Configure, and unsolicited whenever the state changes.
        #[prost(message, tag = "8")]
        ConnectionStatus(super::ConnectionStatus),
    }
}
/// The state of this connection, from the serving node's point of view.
///
/// Sent unsolicited whenever it changes, with request_id zero, because the
/// change a client is usually waiting for is one nobody asked about: a node cut
/// off from the cluster cannot serve writes, and the client needs to know the
/// moment it can again. Holding the session and waiting for that event beats
/// retrying on a timer whose interval is a guess about how long an election
/// takes. It is also the answer to a Configure, where request_id echoes it.
///
/// This describes THIS connection, not the cluster: it is what this node can do
/// for this client right now. The cluster-wide picture, with every node's role
/// and lag, is an operator's view and lives in the admin service.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConnectionStatus {
    /// Whether statements that write can be served through this connection right
    /// now. True on the leader, and true on a follower that can reach the leader,
    /// since a write arriving at a follower is carried there. False when no
    /// leader is reachable, which is the condition a waiting client is watching
    /// for the end of.
    #[prost(bool, tag = "1")]
    pub writable: bool,
    /// Whether this node has contact with the cluster at all. False on a node
    /// that has lost touch with its peers: reads from it still answer, from a
    /// snapshot that no longer advances.
    #[prost(bool, tag = "2")]
    pub connected: bool,
    /// The node the cluster last named leader. Unset while an election is in
    /// flight or this node cannot tell.
    #[prost(uint64, optional, tag = "3")]
    pub leader_id: ::core::option::Option<u64>,
    /// Whether the node serving this connection is itself the leader. A client
    /// that wants to avoid the forwarding hop can use this to decide whether to
    /// reconnect to the leader named above.
    #[prost(bool, tag = "4")]
    pub served_by_leader: bool,
    /// Raft term this status was observed in. Increases at every election, so a
    /// client can tell a genuine leadership change from a repeated report.
    #[prost(uint64, tag = "5")]
    pub raft_term: u64,
    /// Voting members the cluster is configured with.
    #[prost(uint32, tag = "6")]
    pub voters: u32,
    /// Voting members this node currently counts as reachable, including itself.
    /// Compared against `voters`, this is what "the majority is present" means
    /// here, and it is what turns a vague outage into a number an operator and a
    /// client can both act on.
    #[prost(uint32, tag = "7")]
    pub voters_reachable: u32,
    /// The settings in effect for statements that carry none of their own. Echoed
    /// whole so a client can confirm a Configure took effect, rather than assume
    /// the fields it sent are the ones now applied.
    #[prost(message, optional, tag = "8")]
    pub settings: ::core::option::Option<Configure>,
}
/// Acknowledges Begin.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Begun {
    /// Allocated transaction handle, always non-zero. Pass it as Execute.txid and
    /// to Commit / Rollback.
    #[prost(uint64, tag = "1")]
    pub txid: u64,
}
/// Opens a result cursor.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CursorOpen {
    /// Result column names, in result order.
    #[prost(string, repeated, tag = "1")]
    pub columns: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// A batch of result rows for an open cursor. Rows reuse the unary query Row
/// message so a session result and a unary result decode identically.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RowBatch {
    /// Result rows, each a list of property values aligned to CursorOpen.columns.
    #[prost(message, repeated, tag = "1")]
    pub rows: ::prost::alloc::vec::Vec<super::query::Row>,
}
/// Closes a result cursor.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CursorEnd {
    /// Final query statistics for the request. Reuses the unary query stats so the
    /// causal applied-index and write counts decode identically.
    #[prost(message, optional, tag = "1")]
    pub stats: ::core::option::Option<super::query::QueryStats>,
}
/// Acknowledges Commit.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Committed {
    /// Raft log index the commit was applied at on the serving node: the causal
    /// operationTime token a client passes as after_index on later causal reads.
    /// Zero in embedded mode (no Raft cluster).
    #[prost(uint64, tag = "1")]
    pub applied_index: u64,
    /// HLC commit timestamp (microseconds since the Unix epoch) every mutation of
    /// the transaction was applied at. Server-assigned. Equal to the storage
    /// sequence number of the write, so it is the exact snapshot anchor:
    /// `AS OF TIMESTAMP <commit_ts>` sees this transaction and nothing committed
    /// later; a change-stream consumer that has processed it resumes from
    /// `commit_ts + 1`. Present in every mode; a read-only transaction reports
    /// its pinned read timestamp.
    #[prost(uint64, tag = "2")]
    pub commit_ts: u64,
}
/// Reports an error for a request.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SessionError {
    /// Stable numeric error code (mirrors the gRPC status taxonomy used elsewhere
    /// on the server). Lets a client branch on the failure class without parsing
    /// the message text.
    #[prost(uint32, tag = "1")]
    pub code: u32,
    /// Human-readable error detail for logs and diagnostics. Not a stable contract;
    /// branch on code, not on this string.
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Statement ordering policy for an interactive transaction, fixed at Begin.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Ordering {
    /// Treated as ORDERING_ORDERED.
    Unspecified = 0,
    /// Each statement carries a per-transaction monotonic nonce. The client
    /// numbers the chain and may send frames out of wire order; the server
    /// reassembles by nonce in a reorder buffer and applies strictly in nonce
    /// order. A failure at nonce K aborts the transaction.
    Ordered = 1,
    /// The client bursts statements without awaiting; the server applies them
    /// serially in wire-arrival order. The first failing statement rolls the whole
    /// transaction back.
    Unordered = 2,
}
impl Ordering {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ORDERING_UNSPECIFIED",
            Self::Ordered => "ORDERING_ORDERED",
            Self::Unordered => "ORDERING_UNORDERED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ORDERING_UNSPECIFIED" => Some(Self::Unspecified),
            "ORDERING_ORDERED" => Some(Self::Ordered),
            "ORDERING_UNORDERED" => Some(Self::Unordered),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod session_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Multiplexed bidirectional session.
    ///
    /// One long-lived bidirectional stream carries many concurrent operations for a
    /// single client. The client fires a batch of requests into the stream; the
    /// server executes them concurrently and streams results back as independent
    /// cursors, tagged by request id, in completion order rather than send order. An
    /// interactive transaction rides the same session as one interleaved sub-thread
    /// alongside non-transactional requests. The session is sticky to the serving
    /// node for its lifetime. The unary query and transaction RPCs remain the simple
    /// default; this stream is their streaming superset.
    #[derive(Debug, Clone)]
    pub struct SessionServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SessionServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SessionServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SessionServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            SessionServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Open a session. The client sends a stream of ClientFrames (queries and
        /// transaction-control operations); the server returns a stream of
        /// ServerFrames (cursor chunks and transaction acknowledgements), each tagged
        /// with the originating request_id so responses demultiplex out of order.
        pub async fn session(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::ClientFrame>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ServerFrame>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/coordinode.v1.session.SessionService/Session",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("coordinode.v1.session.SessionService", "Session"),
                );
            self.inner.streaming(req, path, codec).await
        }
    }
}
