// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteCypherRequest {
    /// OpenCypher query string.
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    /// Named query parameters bound at execution time.
    #[prost(map = "string, message", tag = "2")]
    pub parameters: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        super::common::PropertyValue,
    >,
    /// Which cluster node may serve this read.
    /// UNSPECIFIED defaults to PRIMARY (leader-only reads).
    /// Use SECONDARY_PREFERRED for read scale-out in 3-node CE cluster.
    #[prost(enumeration = "super::replication::ReadPreference", tag = "3")]
    pub read_preference: i32,
    /// Data consistency guarantee for this read.
    /// UNSPECIFIED defaults to LOCAL (return whatever this node has applied).
    /// Use MAJORITY for reads that must not see rolled-back data.
    /// Use LINEARIZABLE for strictest freshness (leader only, adds ~1 RTT).
    #[prost(message, optional, tag = "4")]
    pub read_concern: ::core::option::Option<super::replication::ReadConcern>,
    /// Durability guarantee for write statements (CREATE / MERGE / SET / DELETE).
    ///
    /// UNSPECIFIED / omitted defaults to W1 (leader-acknowledged, not replicated).
    /// Use MAJORITY for production writes that must survive a single node failure.
    ///
    /// Causal sessions (read_concern.after_index > 0) require write_concern.level
    ///
    /// >
    /// > = MAJORITY. The server rejects writes with lower durability in causal
    /// > sessions because a non-majority write may never be replicated: if the leader
    /// > crashes before drain, the returned applied_index becomes a dangling causal
    /// > dependency that can never be satisfied by a follower read.
    ///
    /// Read-only queries ignore this field.
    #[prost(message, optional, tag = "5")]
    pub write_concern: ::core::option::Option<super::replication::WriteConcern>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteCypherResponse {
    #[prost(string, repeated, tag = "1")]
    pub columns: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "2")]
    pub rows: ::prost::alloc::vec::Vec<Row>,
    #[prost(message, optional, tag = "3")]
    pub stats: ::core::option::Option<QueryStats>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Row {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<super::common::PropertyValue>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryStats {
    #[prost(int64, tag = "1")]
    pub nodes_created: i64,
    #[prost(int64, tag = "2")]
    pub nodes_deleted: i64,
    #[prost(int64, tag = "3")]
    pub edges_created: i64,
    #[prost(int64, tag = "4")]
    pub edges_deleted: i64,
    #[prost(int64, tag = "5")]
    pub properties_set: i64,
    #[prost(int64, tag = "6")]
    pub execution_time_ms: i64,
    /// Raft log index applied on the serving node at query time.
    /// Clients use this as `after_index` in subsequent causal reads (R142).
    /// 0 means the node is not part of a Raft cluster (embedded mode).
    #[prost(uint64, tag = "7")]
    pub applied_index: u64,
    /// True when the read was served by the Raft leader.
    /// False for follower reads (read_preference = SECONDARY or NEAREST).
    #[prost(bool, tag = "8")]
    pub served_by_leader: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExplainCypherRequest {
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    #[prost(map = "string, message", tag = "2")]
    pub parameters: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        super::common::PropertyValue,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExplainCypherResponse {
    #[prost(message, optional, tag = "1")]
    pub plan: ::core::option::Option<QueryPlan>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryPlan {
    #[prost(string, tag = "1")]
    pub operator: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "2")]
    pub details: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, repeated, tag = "3")]
    pub children: ::prost::alloc::vec::Vec<QueryPlan>,
    #[prost(double, tag = "4")]
    pub estimated_rows: f64,
}
/// Generated client implementations.
pub mod cypher_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// OpenCypher-compatible query execution service.
    #[derive(Debug, Clone)]
    pub struct CypherServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl CypherServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> CypherServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CypherServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            CypherServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Execute an OpenCypher query and return results.
        pub async fn execute_cypher(
            &mut self,
            request: impl tonic::IntoRequest<super::ExecuteCypherRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExecuteCypherResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/coordinode.v1.query.CypherService/ExecuteCypher",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("coordinode.v1.query.CypherService", "ExecuteCypher"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Explain an OpenCypher query plan without executing.
        pub async fn explain_cypher(
            &mut self,
            request: impl tonic::IntoRequest<super::ExplainCypherRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExplainCypherResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/coordinode.v1.query.CypherService/ExplainCypher",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("coordinode.v1.query.CypherService", "ExplainCypher"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
