// This file is @generated by prost-build.
/// Write concern configuration for a write statement or a session default.
///
/// Two independent axes, as in MongoDB: `w` (how many members acknowledge) and
/// `journal` (what state each of them holds the write in). `w` is either a
/// count of members or a named mode; the two never share a number space, so
/// `acks: 3` is three members in a group of any size and can never be
/// confused with a mode. Leaving `w` unset selects the default, MAJORITY;
/// asking for fire-and-forget is always explicit (`acks: 0`). Neither axis is
/// ever silently changed to satisfy the other: a combination the server cannot
/// honour is rejected with INVALID_ARGUMENT.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WriteConcern {
    /// The state each counted member holds the write in. Omitted = JOURNAL.
    /// CACHE and MEMORY are accepted only with `acks: 0` or `acks: 1`: a
    /// volatile state cannot be confirmed across members, so combining them
    /// with `acks` above 1 or with MAJORITY is rejected with INVALID_ARGUMENT.
    #[prost(enumeration = "Journal", tag = "6")]
    pub journal: i32,
    /// Time in milliseconds to wait for `w` to be satisfied; 0 = no timeout. On
    /// timeout the call fails, but the write is NOT rolled back: it may still
    /// commit afterwards.
    #[prost(uint32, tag = "3")]
    pub timeout_ms: u32,
    #[prost(oneof = "write_concern::W", tags = "4, 5")]
    pub w: ::core::option::Option<write_concern::W>,
}
/// Nested message and enum types in `WriteConcern`.
pub mod write_concern {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum W {
        /// Number of members, the leader included, that must hold the write in
        /// the `journal` state before the caller is answered. 0 = fire-and-forget:
        /// the write still goes through the leader and the log, the caller is
        /// answered at once and is not told whether it committed. 1 = the leader
        /// alone (rollback possible if the leader fails before replication). N = N
        /// members. A value above the group's member count is rejected with
        /// INVALID_ARGUMENT.
        #[prost(uint32, tag = "4")]
        Acks(u32),
        /// A named rule instead of a count. See WriteConcernMode.
        #[prost(enumeration = "super::WriteConcernMode", tag = "5")]
        Mode(i32),
    }
}
/// Read concern configuration.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadConcern {
    /// Consistency level for this read. UNSPECIFIED defaults to LOCAL.
    #[prost(enumeration = "ReadConcernLevel", tag = "1")]
    pub level: i32,
    /// Causal fence: wait until the serving node has applied log entries up to
    /// at least this Raft log index before executing the read.
    ///
    /// Set to the `QueryStats.applied_index` value from a prior write response
    /// to guarantee read-your-writes: the read is guaranteed to observe all
    /// mutations up to and including that write.
    ///
    /// 0 = no fence (default). Only valid with level = MAJORITY or SNAPSHOT;
    /// returns FAILED_PRECONDITION if level = LOCAL or LINEARIZABLE.
    ///
    /// Has no effect in standalone (non-Raft) mode — all writes are immediately
    /// visible. The returned applied_index will always be 0 in standalone mode,
    /// so clients should not set after_index unless operating in cluster mode.
    #[prost(uint64, tag = "2")]
    pub after_index: u64,
    /// Snapshot pin: read the database as of this HLC timestamp (microseconds
    /// since Unix epoch, leader-assigned).
    ///
    /// Only valid with level = SNAPSHOT. Setting this with any other level
    /// returns FAILED_PRECONDITION. 0 = no pin (latest snapshot of the chosen
    /// level applies).
    ///
    /// Typical use: time-travel reads ("what did this query return at 2026-05-15
    /// 12:00:00?"). The timestamp must be within the MVCC retention window —
    /// older snapshots are GC'd. Reads beyond retention return UNAVAILABLE.
    ///
    /// Distinct from `after_index`: `after_index` is a *fence* (wait until at
    /// least this index is applied), `at_timestamp` is a *pin* (read exactly
    /// this version, no waiting).
    #[prost(uint64, tag = "3")]
    pub at_timestamp: u64,
}
/// Named write concern modes: rules for `w` that are not a fixed count of
/// members.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum WriteConcernMode {
    /// Not a valid choice on the wire: a WriteConcern whose `w` is unset means
    /// the default, MAJORITY. Set `mode` explicitly to one of the values below.
    Unspecified = 0,
    /// Acknowledged once a majority of the group's members (the leader included)
    /// holds the write in the state named by `journal`. Survives the loss of a
    /// minority. The default.
    Majority = 1,
}
impl WriteConcernMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "WRITE_CONCERN_MODE_UNSPECIFIED",
            Self::Majority => "WRITE_CONCERN_MODE_MAJORITY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "WRITE_CONCERN_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            "WRITE_CONCERN_MODE_MAJORITY" => Some(Self::Majority),
            _ => None,
        }
    }
}
/// The state each acknowledging member must hold the write in before it
/// counts towards `w`. Independent of `w`: `w` says how many members, `journal`
/// says how durably each of them holds the write.
///
/// A write concern decides when the caller is answered, never whether the
/// write is replicated: every write enters the group's log through the leader
/// and is applied on every member. CACHE and MEMORY answer before the write is
/// in the log and keep it in a volatile overlay until the drain proposes it;
/// a leader crash before the drain loses every write still in that overlay.
/// Use them for telemetry, hot counters and session state only, never for
/// source-of-truth data.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Journal {
    /// Same as JOURNAL: the default when the field is omitted.
    Unspecified = 0,
    /// The write is fsynced to the member's journal (the Raft log) before it is
    /// counted. Survives process crash and power failure.
    Journal = 1,
    /// The write is in the member's RAM + NVMe overlay (~100µs) before it is
    /// counted. Survives a process crash, not a power failure before the drain.
    Cache = 2,
    /// The write is in the member's RAM-only overlay (~1µs) before it is
    /// counted. Visible at once to local readers that accept volatile data;
    /// lost on process crash before the drain.
    Memory = 3,
}
impl Journal {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "JOURNAL_UNSPECIFIED",
            Self::Journal => "JOURNAL_JOURNAL",
            Self::Cache => "JOURNAL_CACHE",
            Self::Memory => "JOURNAL_MEMORY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "JOURNAL_UNSPECIFIED" => Some(Self::Unspecified),
            "JOURNAL_JOURNAL" => Some(Self::Journal),
            "JOURNAL_CACHE" => Some(Self::Cache),
            "JOURNAL_MEMORY" => Some(Self::Memory),
            _ => None,
        }
    }
}
/// Read concern levels.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ReadConcernLevel {
    Unspecified = 0,
    /// Read from local replica (may be stale).
    Local = 1,
    /// Read data committed by majority.
    Majority = 2,
    /// Linearizable read (strongest guarantee).
    Linearizable = 3,
    /// Read from a consistent MVCC snapshot.
    Snapshot = 4,
}
impl ReadConcernLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "READ_CONCERN_LEVEL_UNSPECIFIED",
            Self::Local => "READ_CONCERN_LEVEL_LOCAL",
            Self::Majority => "READ_CONCERN_LEVEL_MAJORITY",
            Self::Linearizable => "READ_CONCERN_LEVEL_LINEARIZABLE",
            Self::Snapshot => "READ_CONCERN_LEVEL_SNAPSHOT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "READ_CONCERN_LEVEL_UNSPECIFIED" => Some(Self::Unspecified),
            "READ_CONCERN_LEVEL_LOCAL" => Some(Self::Local),
            "READ_CONCERN_LEVEL_MAJORITY" => Some(Self::Majority),
            "READ_CONCERN_LEVEL_LINEARIZABLE" => Some(Self::Linearizable),
            "READ_CONCERN_LEVEL_SNAPSHOT" => Some(Self::Snapshot),
            _ => None,
        }
    }
}
/// Read preference for routing read operations.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ReadPreference {
    Unspecified = 0,
    Primary = 1,
    PrimaryPreferred = 2,
    Secondary = 3,
    SecondaryPreferred = 4,
    Nearest = 5,
}
impl ReadPreference {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "READ_PREFERENCE_UNSPECIFIED",
            Self::Primary => "READ_PREFERENCE_PRIMARY",
            Self::PrimaryPreferred => "READ_PREFERENCE_PRIMARY_PREFERRED",
            Self::Secondary => "READ_PREFERENCE_SECONDARY",
            Self::SecondaryPreferred => "READ_PREFERENCE_SECONDARY_PREFERRED",
            Self::Nearest => "READ_PREFERENCE_NEAREST",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "READ_PREFERENCE_UNSPECIFIED" => Some(Self::Unspecified),
            "READ_PREFERENCE_PRIMARY" => Some(Self::Primary),
            "READ_PREFERENCE_PRIMARY_PREFERRED" => Some(Self::PrimaryPreferred),
            "READ_PREFERENCE_SECONDARY" => Some(Self::Secondary),
            "READ_PREFERENCE_SECONDARY_PREFERRED" => Some(Self::SecondaryPreferred),
            "READ_PREFERENCE_NEAREST" => Some(Self::Nearest),
            _ => None,
        }
    }
}
