// This file is @generated by prost-build.
/// A COMPUTED property specification within a CreateLabelRequest.
///
/// COMPUTED properties are evaluated at query time from node data — no value
/// is stored per node. The spec is stored once in the label schema and applied
/// to all nodes of that label during MATCH/RETURN execution.
///
/// Three types:
/// TTL         — background auto-delete after duration_secs
/// DECAY       — float value interpolated between initial and target over time
/// VECTOR_DECAY — query-time multiplier on vector similarity scores
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ComputedPropertyDefinition {
    /// Property name. Must not collide with regular PropertyDefinition names
    /// in the same label. Convention: prefix TTL properties with underscore
    /// (e.g., "\_ttl", "\_expires").
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Kind of computed property. Required.
    #[prost(enumeration = "ComputedType", tag = "2")]
    pub computed_type: i32,
    /// Decay formula variant. Required for DECAY and VECTOR_DECAY types.
    /// Ignored for TTL type.
    #[prost(enumeration = "DecayFormulaType", tag = "3")]
    pub formula_type: i32,
    /// For EXPONENTIAL formula: pre-computed λ = ln(2) / half_life_fraction.
    /// Example: half-life at 50% of duration → lambda = ln(2) / 0.5 ≈ 1.386.
    #[prost(double, tag = "4")]
    pub lambda: f64,
    /// For POWER_LAW formula: time scale as fraction of duration (τ > 0).
    /// Controls how fast the initial decay is. Smaller τ → faster initial drop.
    #[prost(double, tag = "5")]
    pub tau: f64,
    /// For POWER_LAW formula: decay exponent (α > 0).
    /// Larger α → faster decay overall.
    #[prost(double, tag = "6")]
    pub alpha: f64,
    /// Starting value at elapsed = 0 (for DECAY type only).
    /// Default: 1.0 (full strength at creation).
    #[prost(double, tag = "7")]
    pub initial: f64,
    /// Target value at elapsed ≥ duration_secs (for DECAY type only).
    /// Default: 0.0 (fully decayed at end of duration).
    #[prost(double, tag = "8")]
    pub target: f64,
    /// Duration in seconds: decay occurs over \[0, duration_secs\]; TTL expires after this.
    /// Required for all computed types.
    #[prost(uint64, tag = "9")]
    pub duration_secs: u64,
    /// Name of the TIMESTAMP property to measure elapsed time from.
    /// Must be declared as a regular TIMESTAMP property in the same CreateLabelRequest.
    /// Example: "created_at", "indexed_at", "expires_at".
    #[prost(string, tag = "10")]
    pub anchor_field: ::prost::alloc::string::String,
    /// What to delete when a TTL expires (for TTL type only).
    /// Default (UNSPECIFIED): treated as TTL_SCOPE_TYPE_NODE — delete the whole node.
    #[prost(enumeration = "TtlScopeType", tag = "11")]
    pub scope: i32,
    /// For TTL_SCOPE_TYPE_SUBTREE: the DOCUMENT property to delete on expiry.
    /// The anchor_field timestamp is preserved; only this DOCUMENT property is removed.
    /// Leave empty if scope is FIELD or NODE (ignored in those cases).
    #[prost(string, tag = "12")]
    pub target_field: ::prost::alloc::string::String,
}
/// A node label definition returned by CreateLabel and ListLabels.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Label {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Regular (non-computed) property definitions.
    #[prost(message, repeated, tag = "2")]
    pub properties: ::prost::alloc::vec::Vec<PropertyDefinition>,
    /// Schema version, incremented on each change.
    #[prost(uint64, tag = "3")]
    pub version: u64,
    /// COMPUTED property specifications declared for this label.
    #[prost(message, repeated, tag = "4")]
    pub computed_properties: ::prost::alloc::vec::Vec<ComputedPropertyDefinition>,
    /// Validation and interning mode for this label. STRICT by default.
    #[prost(enumeration = "SchemaMode", tag = "5")]
    pub schema_mode: i32,
}
/// An edge type definition.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EdgeType {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub properties: ::prost::alloc::vec::Vec<PropertyDefinition>,
    #[prost(uint64, tag = "3")]
    pub version: u64,
}
/// A property definition within a label or edge type.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PropertyDefinition {
    /// Property name.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Declared type. COMPUTED properties are represented separately via
    /// ComputedPropertyDefinition; use PropertyType for regular properties only.
    #[prost(enumeration = "PropertyType", tag = "2")]
    pub r#type: i32,
    /// Whether this property is required (NOT NULL). Writes missing this property
    /// are rejected in STRICT and VALIDATED schema modes.
    #[prost(bool, tag = "3")]
    pub required: bool,
    /// Whether a UNIQUE B-tree index is maintained for this property.
    /// Duplicate values across nodes of this label are rejected.
    #[prost(bool, tag = "4")]
    pub unique: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateLabelRequest {
    /// Label name (e.g., "User", "Movie", "Memory").
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Regular property declarations. Defines types, constraints (unique, required).
    #[prost(message, repeated, tag = "2")]
    pub properties: ::prost::alloc::vec::Vec<PropertyDefinition>,
    /// COMPUTED property specifications. The TtlReaper background worker picks up
    /// TTL specs automatically; DECAY and VECTOR_DECAY are evaluated at query time.
    /// These are stored in the label schema and apply to all nodes of this label.
    #[prost(message, repeated, tag = "3")]
    pub computed_properties: ::prost::alloc::vec::Vec<ComputedPropertyDefinition>,
    /// Schema mode controlling validation and interning. Defaults to STRICT when
    /// unspecified. Use FLEXIBLE to replicate schema-free behaviour on a declared
    /// label; use VALIDATED to accept extra properties in an overflow map.
    #[prost(enumeration = "SchemaMode", tag = "4")]
    pub schema_mode: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateEdgeTypeRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub properties: ::prost::alloc::vec::Vec<PropertyDefinition>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListLabelsRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListLabelsResponse {
    #[prost(message, repeated, tag = "1")]
    pub labels: ::prost::alloc::vec::Vec<Label>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListEdgeTypesRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListEdgeTypesResponse {
    #[prost(message, repeated, tag = "1")]
    pub edge_types: ::prost::alloc::vec::Vec<EdgeType>,
}
/// The kind of COMPUTED property.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ComputedType {
    /// Unspecified — invalid, rejected by server.
    Unspecified = 0,
    /// Auto-delete node/property after duration_secs. Background TtlReaper
    /// scans all nodes of this label and deletes those whose anchor_field
    /// timestamp is older than duration_secs.
    Ttl = 1,
    /// Value interpolated between initial and target over duration_secs.
    /// Evaluated inline at query time: value = initial + (target - initial) × formula(elapsed).
    Decay = 2,
    /// Multiplier applied to vector similarity scores at query time.
    /// Evaluated as a float in \[0, 1\] that the planner multiplies with
    /// vector_similarity() results.
    VectorDecay = 3,
}
impl ComputedType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "COMPUTED_TYPE_UNSPECIFIED",
            Self::Ttl => "COMPUTED_TYPE_TTL",
            Self::Decay => "COMPUTED_TYPE_DECAY",
            Self::VectorDecay => "COMPUTED_TYPE_VECTOR_DECAY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMPUTED_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "COMPUTED_TYPE_TTL" => Some(Self::Ttl),
            "COMPUTED_TYPE_DECAY" => Some(Self::Decay),
            "COMPUTED_TYPE_VECTOR_DECAY" => Some(Self::VectorDecay),
            _ => None,
        }
    }
}
/// Decay formula variant for DECAY and VECTOR_DECAY computed types.
/// All formulas map normalized time t ∈ \[0, 1\] to weight ∈ \[0, 1\].
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DecayFormulaType {
    Unspecified = 0,
    /// f(t) = max(0, 1 - t). Constant rate, hard cutoff at duration.
    Linear = 1,
    /// f(t) = e^(-λt). Exponential decay. Requires lambda field.
    /// λ = ln(2) / half_life_fraction; pre-computed by client from desired half-life.
    Exponential = 2,
    /// f(t) = (1 + t/τ)^(-α). Fat-tail decay. Requires tau and alpha fields.
    /// Recent items decay fast; residual value persists longer than exponential.
    PowerLaw = 3,
    /// f(t) = 1 if t \< 1, else 0. Binary step: full value until duration, then zero.
    /// Semantically equivalent to TTL but evaluated at query time (no background delete).
    Step = 4,
}
impl DecayFormulaType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DECAY_FORMULA_TYPE_UNSPECIFIED",
            Self::Linear => "DECAY_FORMULA_TYPE_LINEAR",
            Self::Exponential => "DECAY_FORMULA_TYPE_EXPONENTIAL",
            Self::PowerLaw => "DECAY_FORMULA_TYPE_POWER_LAW",
            Self::Step => "DECAY_FORMULA_TYPE_STEP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DECAY_FORMULA_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "DECAY_FORMULA_TYPE_LINEAR" => Some(Self::Linear),
            "DECAY_FORMULA_TYPE_EXPONENTIAL" => Some(Self::Exponential),
            "DECAY_FORMULA_TYPE_POWER_LAW" => Some(Self::PowerLaw),
            "DECAY_FORMULA_TYPE_STEP" => Some(Self::Step),
            _ => None,
        }
    }
}
/// What to delete when a TTL COMPUTED property expires.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TtlScopeType {
    Unspecified = 0,
    /// Delete only the anchor_field property from the node. Node remains alive.
    Field = 1,
    /// Delete the target_field DOCUMENT property. The anchor_field timestamp
    /// remains intact; only the nested document content is removed. Requires
    /// target_field to be set in ComputedPropertyDefinition.
    Subtree = 2,
    /// Delete the entire node and all its outgoing/incoming edges (DETACH DELETE).
    Node = 3,
}
impl TtlScopeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TTL_SCOPE_TYPE_UNSPECIFIED",
            Self::Field => "TTL_SCOPE_TYPE_FIELD",
            Self::Subtree => "TTL_SCOPE_TYPE_SUBTREE",
            Self::Node => "TTL_SCOPE_TYPE_NODE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TTL_SCOPE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "TTL_SCOPE_TYPE_FIELD" => Some(Self::Field),
            "TTL_SCOPE_TYPE_SUBTREE" => Some(Self::Subtree),
            "TTL_SCOPE_TYPE_NODE" => Some(Self::Node),
            _ => None,
        }
    }
}
/// Schema validation and flexibility mode for a node label.
///
/// Controls how the write path handles properties at CREATE and SET time.
/// Applied per label via CreateLabelRequest.schema_mode.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SchemaMode {
    /// Unspecified — defaults to STRICT on the server.
    Unspecified = 0,
    /// All properties must be declared in the schema. Undeclared properties are
    /// rejected at write time with a schema violation error. Full field-name
    /// interning is applied (up to 80% key storage reduction).
    Strict = 1,
    /// Declared properties are type-checked and interned. Undeclared properties
    /// are accepted and stored in an overflow map (string keys, no interning).
    /// +10–20% storage overhead for undeclared properties.
    Validated = 2,
    /// No schema enforcement. All properties stored with string keys (no
    /// interning). +80% storage overhead vs STRICT. Equivalent to the
    /// schema-free default behaviour on labels without a declared schema.
    Flexible = 3,
}
impl SchemaMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SCHEMA_MODE_UNSPECIFIED",
            Self::Strict => "SCHEMA_MODE_STRICT",
            Self::Validated => "SCHEMA_MODE_VALIDATED",
            Self::Flexible => "SCHEMA_MODE_FLEXIBLE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SCHEMA_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            "SCHEMA_MODE_STRICT" => Some(Self::Strict),
            "SCHEMA_MODE_VALIDATED" => Some(Self::Validated),
            "SCHEMA_MODE_FLEXIBLE" => Some(Self::Flexible),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PropertyType {
    Unspecified = 0,
    Int64 = 1,
    Float64 = 2,
    String = 3,
    Bool = 4,
    Bytes = 5,
    Timestamp = 6,
    Vector = 7,
    List = 8,
    Map = 9,
}
impl PropertyType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROPERTY_TYPE_UNSPECIFIED",
            Self::Int64 => "PROPERTY_TYPE_INT64",
            Self::Float64 => "PROPERTY_TYPE_FLOAT64",
            Self::String => "PROPERTY_TYPE_STRING",
            Self::Bool => "PROPERTY_TYPE_BOOL",
            Self::Bytes => "PROPERTY_TYPE_BYTES",
            Self::Timestamp => "PROPERTY_TYPE_TIMESTAMP",
            Self::Vector => "PROPERTY_TYPE_VECTOR",
            Self::List => "PROPERTY_TYPE_LIST",
            Self::Map => "PROPERTY_TYPE_MAP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROPERTY_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "PROPERTY_TYPE_INT64" => Some(Self::Int64),
            "PROPERTY_TYPE_FLOAT64" => Some(Self::Float64),
            "PROPERTY_TYPE_STRING" => Some(Self::String),
            "PROPERTY_TYPE_BOOL" => Some(Self::Bool),
            "PROPERTY_TYPE_BYTES" => Some(Self::Bytes),
            "PROPERTY_TYPE_TIMESTAMP" => Some(Self::Timestamp),
            "PROPERTY_TYPE_VECTOR" => Some(Self::Vector),
            "PROPERTY_TYPE_LIST" => Some(Self::List),
            "PROPERTY_TYPE_MAP" => Some(Self::Map),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod schema_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Schema management operations.
    #[derive(Debug, Clone)]
    pub struct SchemaServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SchemaServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SchemaServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SchemaServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            SchemaServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Create a new node label with property definitions.
        pub async fn create_label(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateLabelRequest>,
        ) -> std::result::Result<tonic::Response<super::Label>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/coordinode.v1.graph.SchemaService/CreateLabel",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("coordinode.v1.graph.SchemaService", "CreateLabel"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Create a new edge type with property definitions.
        pub async fn create_edge_type(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateEdgeTypeRequest>,
        ) -> std::result::Result<tonic::Response<super::EdgeType>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/coordinode.v1.graph.SchemaService/CreateEdgeType",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "coordinode.v1.graph.SchemaService",
                        "CreateEdgeType",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// List all labels in the schema.
        pub async fn list_labels(
            &mut self,
            request: impl tonic::IntoRequest<super::ListLabelsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListLabelsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/coordinode.v1.graph.SchemaService/ListLabels",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("coordinode.v1.graph.SchemaService", "ListLabels"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// List all edge types in the schema.
        pub async fn list_edge_types(
            &mut self,
            request: impl tonic::IntoRequest<super::ListEdgeTypesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListEdgeTypesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/coordinode.v1.graph.SchemaService/ListEdgeTypes",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("coordinode.v1.graph.SchemaService", "ListEdgeTypes"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
