// This file is @generated by prost-build.
/// Write concern configuration.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WriteConcern {
    #[prost(enumeration = "WriteConcernLevel", tag = "1")]
    pub level: i32,
    /// Require WAL fsync before acknowledgement.
    #[prost(bool, tag = "2")]
    pub journal: bool,
    /// Timeout in milliseconds (0 = no timeout).
    #[prost(uint32, tag = "3")]
    pub timeout_ms: u32,
}
/// Read concern configuration.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadConcern {
    /// Consistency level for this read. UNSPECIFIED defaults to LOCAL.
    #[prost(enumeration = "ReadConcernLevel", tag = "1")]
    pub level: i32,
    /// Causal fence: wait until the serving node has applied log entries up to
    /// at least this Raft log index before executing the read.
    ///
    /// Set to the `QueryStats.applied_index` value from a prior write response
    /// to guarantee read-your-writes: the read is guaranteed to observe all
    /// mutations up to and including that write.
    ///
    /// 0 = no fence (default). Only valid with level = MAJORITY or SNAPSHOT;
    /// returns FAILED_PRECONDITION if level = LOCAL or LINEARIZABLE.
    ///
    /// Has no effect in standalone (non-Raft) mode — all writes are immediately
    /// visible. The returned applied_index will always be 0 in standalone mode,
    /// so clients should not set after_index unless operating in cluster mode.
    #[prost(uint64, tag = "2")]
    pub after_index: u64,
}
/// Write concern levels.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum WriteConcernLevel {
    Unspecified = 0,
    /// Fire-and-forget (no acknowledgement).
    W0 = 1,
    /// Acknowledged by leader only.
    W1 = 2,
    /// Acknowledged by majority of replicas.
    Majority = 3,
}
impl WriteConcernLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "WRITE_CONCERN_LEVEL_UNSPECIFIED",
            Self::W0 => "WRITE_CONCERN_LEVEL_W0",
            Self::W1 => "WRITE_CONCERN_LEVEL_W1",
            Self::Majority => "WRITE_CONCERN_LEVEL_MAJORITY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "WRITE_CONCERN_LEVEL_UNSPECIFIED" => Some(Self::Unspecified),
            "WRITE_CONCERN_LEVEL_W0" => Some(Self::W0),
            "WRITE_CONCERN_LEVEL_W1" => Some(Self::W1),
            "WRITE_CONCERN_LEVEL_MAJORITY" => Some(Self::Majority),
            _ => None,
        }
    }
}
/// Read concern levels.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ReadConcernLevel {
    Unspecified = 0,
    /// Read from local replica (may be stale).
    Local = 1,
    /// Read data committed by majority.
    Majority = 2,
    /// Linearizable read (strongest guarantee).
    Linearizable = 3,
    /// Read from a consistent MVCC snapshot.
    Snapshot = 4,
}
impl ReadConcernLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "READ_CONCERN_LEVEL_UNSPECIFIED",
            Self::Local => "READ_CONCERN_LEVEL_LOCAL",
            Self::Majority => "READ_CONCERN_LEVEL_MAJORITY",
            Self::Linearizable => "READ_CONCERN_LEVEL_LINEARIZABLE",
            Self::Snapshot => "READ_CONCERN_LEVEL_SNAPSHOT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "READ_CONCERN_LEVEL_UNSPECIFIED" => Some(Self::Unspecified),
            "READ_CONCERN_LEVEL_LOCAL" => Some(Self::Local),
            "READ_CONCERN_LEVEL_MAJORITY" => Some(Self::Majority),
            "READ_CONCERN_LEVEL_LINEARIZABLE" => Some(Self::Linearizable),
            "READ_CONCERN_LEVEL_SNAPSHOT" => Some(Self::Snapshot),
            _ => None,
        }
    }
}
/// Read preference for routing read operations.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ReadPreference {
    Unspecified = 0,
    Primary = 1,
    PrimaryPreferred = 2,
    Secondary = 3,
    SecondaryPreferred = 4,
    Nearest = 5,
}
impl ReadPreference {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "READ_PREFERENCE_UNSPECIFIED",
            Self::Primary => "READ_PREFERENCE_PRIMARY",
            Self::PrimaryPreferred => "READ_PREFERENCE_PRIMARY_PREFERRED",
            Self::Secondary => "READ_PREFERENCE_SECONDARY",
            Self::SecondaryPreferred => "READ_PREFERENCE_SECONDARY_PREFERRED",
            Self::Nearest => "READ_PREFERENCE_NEAREST",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "READ_PREFERENCE_UNSPECIFIED" => Some(Self::Unspecified),
            "READ_PREFERENCE_PRIMARY" => Some(Self::Primary),
            "READ_PREFERENCE_PRIMARY_PREFERRED" => Some(Self::PrimaryPreferred),
            "READ_PREFERENCE_SECONDARY" => Some(Self::Secondary),
            "READ_PREFERENCE_SECONDARY_PREFERRED" => Some(Self::SecondaryPreferred),
            "READ_PREFERENCE_NEAREST" => Some(Self::Nearest),
            _ => None,
        }
    }
}
