// This file is @generated by prost-build.
/// Unique identifier for a node in the graph.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NodeId {
    #[prost(uint64, tag = "1")]
    pub id: u64,
}
/// Unique identifier for an edge in the graph.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EdgeId {
    #[prost(uint64, tag = "1")]
    pub id: u64,
}
/// Hybrid Logical Clock timestamp.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HlcTimestamp {
    #[prost(uint64, tag = "1")]
    pub wall_time: u64,
    #[prost(uint32, tag = "2")]
    pub logical: u32,
}
/// A typed property value (oneof for all supported types).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PropertyValue {
    #[prost(oneof = "property_value::Value", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9")]
    pub value: ::core::option::Option<property_value::Value>,
}
/// Nested message and enum types in `PropertyValue`.
pub mod property_value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(int64, tag = "1")]
        IntValue(i64),
        #[prost(double, tag = "2")]
        FloatValue(f64),
        #[prost(string, tag = "3")]
        StringValue(::prost::alloc::string::String),
        #[prost(bool, tag = "4")]
        BoolValue(bool),
        #[prost(bytes, tag = "5")]
        BytesValue(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag = "6")]
        TimestampValue(super::HlcTimestamp),
        #[prost(message, tag = "7")]
        VectorValue(super::Vector),
        #[prost(message, tag = "8")]
        ListValue(super::PropertyList),
        #[prost(message, tag = "9")]
        MapValue(super::PropertyMap),
    }
}
/// A dense float vector for vector search.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Vector {
    #[prost(float, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<f32>,
}
/// A list of property values (homogeneous arrays).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PropertyList {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<PropertyValue>,
}
/// A map of string keys to property values.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PropertyMap {
    #[prost(map = "string, message", tag = "1")]
    pub entries: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        PropertyValue,
    >,
}
