//! Generated proto module stubs.
//!
//! The `include!` macros pull in code generated by build.rs from the
//! proto/ submodule. Because coordinode-server uses `build_server=true`
//! and we set `build_client=true`, both sides are usable here.

// Suppress warnings from generated code outside our control.
#[allow(clippy::all, dead_code)]
pub mod common {
    include!(concat!(env!("OUT_DIR"), "/coordinode.v1.common.rs"));
}

#[allow(clippy::all, dead_code)]
pub mod graph {
    include!(concat!(env!("OUT_DIR"), "/coordinode.v1.graph.rs"));
}

#[allow(clippy::all, dead_code)]
pub mod replication {
    include!(concat!(env!("OUT_DIR"), "/coordinode.v1.replication.rs"));
}

#[allow(clippy::all, dead_code)]
pub mod query {
    include!(concat!(env!("OUT_DIR"), "/coordinode.v1.query.rs"));
}
