//! # CoordiNode Rust Client
//!
//! Official Rust gRPC driver for CoordiNode with optional source location
//! tracking for the Query Advisor.
//!
//! ## Quick start
//!
//! ```no_run
//! # tokio_test::block_on(async {
//! use coordinode_client::CoordinodeClient;
//!
//! let mut client = CoordinodeClient::connect("http://localhost:7080")
//!     .await
//!     .unwrap();
//!
//! let rows = client.execute_cypher("MATCH (n:Person) RETURN n.name LIMIT 5")
//!     .await
//!     .unwrap();
//!
//! for row in rows {
//!     println!("{:?}", row);
//! }
//! # })
//! ```
//!
//! ## Source location tracking
//!
//! Enable `debug_source_tracking` in development to let the server's Query
//! Advisor map slow-query suggestions to exact call sites in your application:
//!
//! ```no_run
//! # tokio_test::block_on(async {
//! use coordinode_client::CoordinodeClient;
//!
//! let mut client = CoordinodeClient::builder("http://localhost:7080")
//!     .debug_source_tracking(true)   // ← attach file:line to every query
//!     .app_name("my-service")
//!     .app_version(env!("CARGO_PKG_VERSION"))
//!     .build()
//!     .await
//!     .unwrap();
//!
//! // The gRPC request will include:
//! //   x-source-file: "src/api/handlers/feed.rs"
//! //   x-source-line: "47"
//! //   x-source-app:  "my-service"
//! let rows = client.execute_cypher("MATCH (u:User)-[:FOLLOWS]->(f) RETURN f LIMIT 10")
//!     .await
//!     .unwrap();
//! # })
//! ```
//!
//! Source tracking relies on Rust's built-in `#[track_caller]` attribute.
//! No macros are needed — simply call the normal client methods and the
//! driver infers the caller's `file:line` automatically.

pub mod config;
pub mod error;
mod source;
mod value;

pub use config::{ClientConfig, CoordinodeClientBuilder};
pub use error::ClientError;
pub use value::Value;

/// Opaque causal consistency token.
///
/// Returned by [`CoordinodeClient::execute_causal_write`] and consumed by
/// [`CoordinodeClient::execute_causal_read`] to enforce read-your-writes
/// ordering in a cluster.
///
/// The token wraps the Raft log index (`applied_index`) that the write was
/// committed at on the serving leader. Passing it to a subsequent read
/// guarantees that read will not be served until the replica has applied at
/// least that log entry — even if the request is routed to a follower.
///
/// ## Standalone / embedded mode
///
/// In non-cluster deployments the server always returns `applied_index = 0`.
/// Reads with a zero-valued token have no fence effect — they succeed
/// immediately. You can safely use the causal API in standalone mode; it just
/// has no observable effect on ordering.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct CausalToken(u64);

impl CausalToken {
    /// The underlying Raft log index.
    pub fn as_u64(self) -> u64 {
        self.0
    }
}

impl From<u64> for CausalToken {
    fn from(index: u64) -> Self {
        Self(index)
    }
}

use std::collections::HashMap;
use std::future::Future;
use std::panic::Location;

// Proto modules generated by build.rs from the proto/ submodule.
// Generated code has clippy warnings that are outside our control.
#[allow(clippy::all, dead_code)]
mod proto {
    pub mod common {
        include!(concat!(env!("OUT_DIR"), "/coordinode.v1.common.rs"));
    }
    pub mod graph {
        include!(concat!(env!("OUT_DIR"), "/coordinode.v1.graph.rs"));
    }
    // Replication types (ReadPreference, ReadConcern, WriteConcern).
    // Required because cypher.proto imports consistency.proto and the generated
    // query code resolves ReadConcern/ReadPreference via `super::replication::`.
    pub mod replication {
        include!(concat!(env!("OUT_DIR"), "/coordinode.v1.replication.rs"));
    }
    pub mod query {
        include!(concat!(env!("OUT_DIR"), "/coordinode.v1.query.rs"));
    }
}

use proto::{
    query::{cypher_service_client::CypherServiceClient, ExecuteCypherRequest},
    replication::{ReadConcern, ReadConcernLevel, WriteConcern, WriteConcernLevel},
};

/// A single result row: column name → property value.
pub type Row = HashMap<String, Value>;

/// CoordiNode gRPC client.
///
/// Create with [`CoordinodeClient::connect`] or [`CoordinodeClient::builder`].
/// All query methods are `#[track_caller]` — when `debug_source_tracking` is
/// enabled the caller's `file:line` is automatically sent to the server.
pub struct CoordinodeClient {
    config: ClientConfig,
    cypher: CypherServiceClient<tonic::transport::Channel>,
}

impl CoordinodeClient {
    // ── Constructors ──────────────────────────────────────────────────────────

    /// Connect to `endpoint` with default settings (no source tracking).
    ///
    /// Equivalent to `CoordinodeClient::builder(endpoint).build().await`.
    pub async fn connect(endpoint: impl Into<String>) -> Result<Self, ClientError> {
        CoordinodeClientBuilder::new(endpoint).build().await
    }

    /// Return a builder to configure the client before connecting.
    pub fn builder(endpoint: impl Into<String>) -> CoordinodeClientBuilder {
        CoordinodeClientBuilder::new(endpoint)
    }

    /// Internal: connect using a fully-built [`ClientConfig`].
    pub(crate) async fn connect_with_config(config: ClientConfig) -> Result<Self, ClientError> {
        let channel = tonic::transport::Channel::from_shared(config.endpoint.clone())
            .map_err(|e| ClientError::InvalidEndpoint(e.to_string()))?
            .connect()
            .await?;

        let cypher = CypherServiceClient::new(channel);

        Ok(Self { config, cypher })
    }

    // ── Cypher ────────────────────────────────────────────────────────────────

    /// Execute a Cypher query with no parameters.
    ///
    /// When `debug_source_tracking` is enabled, the caller's source location
    /// is attached to the request automatically via `#[track_caller]`.
    ///
    /// # Note on `#[track_caller]` and async
    ///
    /// Rust does not yet stabilise `#[track_caller]` on `async fn` (rust-lang/rust#110011).
    /// This method is therefore a synchronous `#[track_caller]` wrapper that captures
    /// `Location::caller()` before delegating to the async implementation. From the
    /// caller's perspective the API is unchanged: `client.execute_cypher(...).await`.
    #[track_caller]
    pub fn execute_cypher(
        &mut self,
        query: impl Into<String>,
    ) -> impl Future<Output = Result<Vec<Row>, ClientError>> + '_ {
        // Location is captured HERE — in the synchronous, #[track_caller] wrapper —
        // so it points to the user's call site, not to driver internals.
        let location = if self.config.debug_source_tracking {
            Some(Location::caller())
        } else {
            None
        };
        self.execute_cypher_inner(query.into(), HashMap::new(), location)
    }

    /// Execute a Cypher query with named parameters.
    ///
    /// ```no_run
    /// # tokio_test::block_on(async {
    /// # use std::collections::HashMap;
    /// # use coordinode_client::{CoordinodeClient, Value};
    /// # let mut client = CoordinodeClient::connect("http://localhost:7080").await.unwrap();
    /// let mut params = HashMap::new();
    /// params.insert("id".to_string(), Value::Int(42));
    ///
    /// let rows = client.execute_cypher_with_params(
    ///     "MATCH (u:User {id: $id}) RETURN u.name",
    ///     params,
    /// ).await.unwrap();
    /// # })
    /// ```
    #[track_caller]
    pub fn execute_cypher_with_params(
        &mut self,
        query: impl Into<String>,
        params: HashMap<String, Value>,
    ) -> impl Future<Output = Result<Vec<Row>, ClientError>> + '_ {
        let location = if self.config.debug_source_tracking {
            Some(Location::caller())
        } else {
            None
        };
        self.execute_cypher_inner(query.into(), params, location)
    }

    // ── Causal consistency ────────────────────────────────────────────────────

    /// Execute a write with **majority durability**, returning a causal token.
    ///
    /// The write is acknowledged only after a quorum of replicas has applied
    /// it to their Raft log. The returned [`CausalToken`] wraps the committed
    /// log index and can be passed to [`execute_causal_read`] to enforce
    /// read-your-writes ordering — even when the read is served by a follower.
    ///
    /// **Standalone / embedded mode:** the token is always `0` (the server
    /// operates without Raft). Passing it to a causal read has no fence effect.
    ///
    /// # Errors
    ///
    /// Returns `ClientError::Grpc` if the server rejects the request (e.g. the
    /// node is not the Raft leader, or `read_concern.after_index` is set with
    /// a non-majority write concern).
    ///
    /// [`execute_causal_read`]: CoordinodeClient::execute_causal_read
    #[track_caller]
    pub fn execute_causal_write(
        &mut self,
        query: impl Into<String>,
    ) -> impl Future<Output = Result<(Vec<Row>, CausalToken), ClientError>> + '_ {
        let location = if self.config.debug_source_tracking {
            Some(Location::caller())
        } else {
            None
        };
        self.execute_causal_write_inner(query.into(), HashMap::new(), location)
    }

    /// Execute a write with **majority durability** and named parameters.
    ///
    /// Identical to [`execute_causal_write`] but accepts query parameters.
    ///
    /// [`execute_causal_write`]: CoordinodeClient::execute_causal_write
    #[track_caller]
    pub fn execute_causal_write_with_params(
        &mut self,
        query: impl Into<String>,
        params: HashMap<String, Value>,
    ) -> impl Future<Output = Result<(Vec<Row>, CausalToken), ClientError>> + '_ {
        let location = if self.config.debug_source_tracking {
            Some(Location::caller())
        } else {
            None
        };
        self.execute_causal_write_inner(query.into(), params, location)
    }

    /// Execute a read that is guaranteed to observe the write identified by
    /// `after`.
    ///
    /// The serving node waits until its applied log index is ≥ `after.as_u64()`
    /// before executing the read. This guarantees **read-your-writes** and
    /// **monotonic reads** when the write was issued with
    /// [`execute_causal_write`].
    ///
    /// Use `ReadPreference::SECONDARY_PREFERRED` in combination with this
    /// method to scale out reads while preserving causal ordering.
    ///
    /// **Standalone / embedded mode:** the fence has no effect (the server
    /// returns immediately).
    ///
    /// [`execute_causal_write`]: CoordinodeClient::execute_causal_write
    #[track_caller]
    pub fn execute_causal_read(
        &mut self,
        query: impl Into<String>,
        after: CausalToken,
    ) -> impl Future<Output = Result<Vec<Row>, ClientError>> + '_ {
        let location = if self.config.debug_source_tracking {
            Some(Location::caller())
        } else {
            None
        };
        self.execute_causal_read_inner(query.into(), HashMap::new(), after, location)
    }

    /// Execute a causal read with named parameters.
    ///
    /// Identical to [`execute_causal_read`] but accepts query parameters.
    ///
    /// [`execute_causal_read`]: CoordinodeClient::execute_causal_read
    #[track_caller]
    pub fn execute_causal_read_with_params(
        &mut self,
        query: impl Into<String>,
        params: HashMap<String, Value>,
        after: CausalToken,
    ) -> impl Future<Output = Result<Vec<Row>, ClientError>> + '_ {
        let location = if self.config.debug_source_tracking {
            Some(Location::caller())
        } else {
            None
        };
        self.execute_causal_read_inner(query.into(), params, after, location)
    }

    // ── Config access ─────────────────────────────────────────────────────────

    /// Returns `true` when source location tracking is enabled.
    pub fn source_tracking_enabled(&self) -> bool {
        self.config.debug_source_tracking
    }

    // ── Internals ─────────────────────────────────────────────────────────────

    async fn execute_cypher_inner(
        &mut self,
        query: String,
        params: HashMap<String, Value>,
        location: Option<&'static Location<'static>>,
    ) -> Result<Vec<Row>, ClientError> {
        let (rows, _applied_index) = self
            .execute_request(
                query, params, 0,    // read_preference = PRIMARY
                None, // read_concern = LOCAL (default)
                None, // write_concern = W1 (default)
                location,
            )
            .await?;
        Ok(rows)
    }

    async fn execute_causal_write_inner(
        &mut self,
        query: String,
        params: HashMap<String, Value>,
        location: Option<&'static Location<'static>>,
    ) -> Result<(Vec<Row>, CausalToken), ClientError> {
        let write_concern = Some(WriteConcern {
            level: WriteConcernLevel::Majority as i32,
            journal: false,
            timeout_ms: 0,
        });
        let (rows, applied_index) = self
            .execute_request(query, params, 0, None, write_concern, location)
            .await?;
        Ok((rows, CausalToken(applied_index)))
    }

    async fn execute_causal_read_inner(
        &mut self,
        query: String,
        params: HashMap<String, Value>,
        after: CausalToken,
        location: Option<&'static Location<'static>>,
    ) -> Result<Vec<Row>, ClientError> {
        let read_concern = Some(ReadConcern {
            level: ReadConcernLevel::Majority as i32,
            after_index: after.as_u64(),
        });
        let (rows, _applied_index) = self
            .execute_request(query, params, 0, read_concern, None, location)
            .await?;
        Ok(rows)
    }

    /// Low-level request executor shared by all public methods.
    ///
    /// Returns the decoded rows **and** the `applied_index` from `QueryStats`
    /// so causal methods can wrap it in a [`CausalToken`].
    async fn execute_request(
        &mut self,
        query: String,
        params: HashMap<String, Value>,
        read_preference: i32,
        read_concern: Option<ReadConcern>,
        write_concern: Option<WriteConcern>,
        location: Option<&'static Location<'static>>,
    ) -> Result<(Vec<Row>, u64), ClientError> {
        let proto_params = params
            .into_iter()
            .map(|(k, v)| (k, value::to_proto(v)))
            .collect();

        let mut request = tonic::Request::new(ExecuteCypherRequest {
            query,
            parameters: proto_params,
            read_preference,
            read_concern,
            write_concern,
        });

        if let Some(loc) = location {
            source::inject_grpc_metadata(request.metadata_mut(), loc, &self.config);
        }

        let response = self.cypher.execute_cypher(request).await?;
        let body = response.into_inner();

        let applied_index = body.stats.as_ref().map_or(0, |s| s.applied_index);

        let columns = body.columns;
        let rows = body
            .rows
            .into_iter()
            .map(|row| {
                columns
                    .iter()
                    .zip(row.values)
                    .map(|(col, pv)| (col.clone(), value::from_proto(pv)))
                    .collect::<Row>()
            })
            .collect();

        Ok((rows, applied_index))
    }
}

// ── Unit tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    /// Builder defaults: source tracking disabled, empty app fields.
    #[test]
    fn builder_defaults() {
        let builder = CoordinodeClient::builder("http://localhost:7080");
        // Build into config directly for inspection
        let config = ClientConfig {
            endpoint: "http://localhost:7080".into(),
            debug_source_tracking: builder.debug_source_tracking,
            app_name: builder.app_name.clone(),
            app_version: builder.app_version.clone(),
        };
        assert!(
            !config.debug_source_tracking,
            "tracking disabled by default"
        );
        assert!(config.app_name.is_empty());
        assert!(config.app_version.is_empty());
    }

    /// Builder properly stores configured values.
    #[test]
    fn builder_custom() {
        let builder = CoordinodeClient::builder("http://prod:7080")
            .debug_source_tracking(true)
            .app_name("my-svc")
            .app_version("v2.0");

        assert!(builder.debug_source_tracking);
        assert_eq!(builder.app_name, "my-svc");
        assert_eq!(builder.app_version, "v2.0");
        assert_eq!(builder.endpoint, "http://prod:7080");
    }

    /// source_tracking_enabled reflects the config.
    ///
    /// We test through the config struct directly (no live server needed).
    #[test]
    fn source_tracking_flag_reflects_config() {
        let config_on = ClientConfig {
            endpoint: "http://localhost:7080".into(),
            debug_source_tracking: true,
            app_name: String::new(),
            app_version: String::new(),
        };
        let config_off = ClientConfig {
            debug_source_tracking: false,
            ..config_on.clone()
        };

        // Build a minimal client without connecting (just check the flag)
        // We can't call connect() without a server, so test via config fields.
        assert!(config_on.debug_source_tracking);
        assert!(!config_off.debug_source_tracking);
    }

    /// Location is captured from the real call site when tracking is on.
    ///
    /// Validates #[track_caller] semantics: the location should point to
    /// THIS test file, not to lib.rs internals.
    #[test]
    fn track_caller_captures_call_site() {
        // Simulate what the execute methods do:
        // Mark this function itself as the "caller" by calling Location::caller()
        // at the point where execute_cypher would call it.
        let tracking_enabled = true;

        #[track_caller]
        fn simulate_execute(enabled: bool) -> Option<&'static Location<'static>> {
            // Must call Location::caller() directly here — passing it as a
            // function pointer to bool::then() loses track_caller propagation
            // because the call goes through FnOnce in function.rs.
            if enabled {
                Some(Location::caller())
            } else {
                None
            }
        }

        let loc = simulate_execute(tracking_enabled);
        assert!(loc.is_some());
        let loc = loc.unwrap();

        // The location must point to this test file (not to the simulate_execute body).
        assert!(
            loc.file().contains("lib.rs"),
            "expected call site in lib.rs, got: {}",
            loc.file()
        );
        assert!(loc.line() > 0);
    }

    /// When tracking is disabled, no location is captured.
    #[test]
    fn track_caller_disabled() {
        #[track_caller]
        fn simulate_execute(enabled: bool) -> Option<&'static Location<'static>> {
            if enabled {
                Some(Location::caller())
            } else {
                None
            }
        }

        let loc = simulate_execute(false);
        assert!(loc.is_none());
    }

    /// invalid endpoint URI returns ClientError::InvalidEndpoint, not a panic.
    #[tokio::test]
    async fn connect_invalid_endpoint_returns_error() {
        let result = CoordinodeClient::connect("not a valid uri !!!").await;
        assert!(
            matches!(result, Err(ClientError::InvalidEndpoint(_))),
            "expected InvalidEndpoint error"
        );
    }

    // ── CausalToken tests ─────────────────────────────────────────────────────

    /// CausalToken wraps the log index and exposes it via as_u64.
    #[test]
    fn causal_token_as_u64() {
        let token = CausalToken(42);
        assert_eq!(token.as_u64(), 42);
    }

    /// CausalToken::from(u64) round-trips through as_u64.
    #[test]
    fn causal_token_from_u64() {
        let token = CausalToken::from(100);
        assert_eq!(token.as_u64(), 100);
    }

    /// Zero token (standalone mode) is a valid value.
    #[test]
    fn causal_token_zero() {
        let token = CausalToken::from(0);
        assert_eq!(token.as_u64(), 0);
    }

    /// CausalToken ordering: higher index = happens-after.
    #[test]
    fn causal_token_ordering() {
        let earlier = CausalToken(10);
        let later = CausalToken(20);
        assert!(later > earlier);
        assert!(earlier < later);
        assert_eq!(earlier, CausalToken(10));
    }

    /// CausalToken is Copy: can be used multiple times without moving.
    #[test]
    fn causal_token_is_copy() {
        let token = CausalToken(7);
        // If CausalToken were not Copy, the second line would fail to compile.
        let _a = token;
        let _b = token;
        assert_eq!(_a, _b);
    }
}
