//! # CoordiNode Rust Client
//!
//! Official Rust gRPC driver for CoordiNode with optional source location
//! tracking for the Query Advisor.
//!
//! ## Quick start
//!
//! ```no_run
//! # tokio_test::block_on(async {
//! use coordinode_client::CoordinodeClient;
//!
//! let mut client = CoordinodeClient::connect("http://localhost:7080")
//!     .await
//!     .unwrap();
//!
//! let rows = client.execute_cypher("MATCH (n:Person) RETURN n.name LIMIT 5")
//!     .await
//!     .unwrap();
//!
//! for row in rows {
//!     println!("{:?}", row);
//! }
//! # })
//! ```
//!
//! ## Source location tracking
//!
//! Enable `debug_source_tracking` in development to let the server's Query
//! Advisor map slow-query suggestions to exact call sites in your application:
//!
//! ```no_run
//! # tokio_test::block_on(async {
//! use coordinode_client::CoordinodeClient;
//!
//! let mut client = CoordinodeClient::builder("http://localhost:7080")
//!     .debug_source_tracking(true)   // ← attach file:line to every query
//!     .app_name("my-service")
//!     .app_version(env!("CARGO_PKG_VERSION"))
//!     .build()
//!     .await
//!     .unwrap();
//!
//! // The gRPC request will include:
//! //   x-source-file: "src/api/handlers/feed.rs"
//! //   x-source-line: "47"
//! //   x-source-app:  "my-service"
//! let rows = client.execute_cypher("MATCH (u:User)-[:FOLLOWS]->(f) RETURN f LIMIT 10")
//!     .await
//!     .unwrap();
//! # })
//! ```
//!
//! Source tracking relies on Rust's built-in `#[track_caller]` attribute.
//! No macros are needed — simply call the normal client methods and the
//! driver infers the caller's `file:line` automatically.

pub mod config;
pub mod error;
mod source;
mod value;

pub use config::{ClientConfig, CoordinodeClientBuilder};
pub use error::ClientError;
pub use value::Value;

/// Opaque causal consistency token.
///
/// Returned by [`CoordinodeClient::execute_causal_write`] and consumed by
/// [`CoordinodeClient::execute_causal_read`] to enforce read-your-writes
/// ordering in a cluster.
///
/// The token wraps the Raft log index (`applied_index`) that the write was
/// committed at on the serving leader. Passing it to a subsequent read
/// guarantees that read will not be served until the replica has applied at
/// least that log entry — even if the request is routed to a follower.
///
/// ## Standalone / embedded mode
///
/// In non-cluster deployments the server always returns `applied_index = 0`.
/// Reads with a zero-valued token have no fence effect — they succeed
/// immediately. You can safely use the causal API in standalone mode; it just
/// has no observable effect on ordering.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct CausalToken(u64);

impl CausalToken {
    /// The underlying Raft log index.
    pub fn as_u64(self) -> u64 {
        self.0
    }
}

impl From<u64> for CausalToken {
    fn from(index: u64) -> Self {
        Self(index)
    }
}

use std::collections::HashMap;
use std::future::Future;
use std::panic::Location;

// Proto modules generated by build.rs from the proto/ submodule.
// Generated code has clippy warnings that are outside our control.
#[allow(clippy::all, dead_code)]
mod proto {
    pub mod common {
        include!(concat!(env!("OUT_DIR"), "/coordinode.v1.common.rs"));
    }
    pub mod graph {
        include!(concat!(env!("OUT_DIR"), "/coordinode.v1.graph.rs"));
    }
    // Replication types (ReadPreference, ReadConcern, WriteConcern).
    // Required because cypher.proto imports consistency.proto and the generated
    // query code resolves ReadConcern/ReadPreference via `super::replication::`.
    pub mod replication {
        include!(concat!(env!("OUT_DIR"), "/coordinode.v1.replication.rs"));
    }
    pub mod query {
        include!(concat!(env!("OUT_DIR"), "/coordinode.v1.query.rs"));
    }
}

use proto::{
    query::{cypher_service_client::CypherServiceClient, ExecuteCypherRequest},
    replication::{ReadConcern, ReadConcernLevel, WriteConcern, WriteConcernLevel},
};

/// Routing preference for read queries in a replicated cluster.
///
/// Mirrors the wire-level `ReadPreference`: [`Primary`] reads always
/// execute on the Raft leader (strongest freshness), the other
/// variants allow follower nodes to serve the read for scale-out.
/// Follower reads observe the follower's applied state; combine with
/// [`CoordinodeClient::execute_causal_read`] when read-your-writes is
/// required.
///
/// [`Primary`]: ReadPreference::Primary
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ReadPreference {
    /// Read from the Raft leader only (default). Fails on followers.
    #[default]
    Primary,
    /// Prefer the leader, fall back to this node when it is a follower.
    PrimaryPreferred,
    /// Read from a follower only. Fails on the leader.
    Secondary,
    /// Prefer a follower, also accept the leader.
    SecondaryPreferred,
    /// Read from whichever node serves the connection.
    Nearest,
}

impl ReadPreference {
    fn to_proto(self) -> i32 {
        use proto::replication::ReadPreference as Wire;
        match self {
            ReadPreference::Primary => Wire::Primary as i32,
            ReadPreference::PrimaryPreferred => Wire::PrimaryPreferred as i32,
            ReadPreference::Secondary => Wire::Secondary as i32,
            ReadPreference::SecondaryPreferred => Wire::SecondaryPreferred as i32,
            ReadPreference::Nearest => Wire::Nearest as i32,
        }
    }
}

/// A single result row: column name → property value.
pub type Row = HashMap<String, Value>;

/// CoordiNode gRPC client.
///
/// Create with [`CoordinodeClient::connect`] or [`CoordinodeClient::builder`].
/// All query methods are `#[track_caller]` — when `debug_source_tracking` is
/// enabled the caller's `file:line` is automatically sent to the server.
pub struct CoordinodeClient {
    config: ClientConfig,
    cypher: CypherServiceClient<tonic::transport::Channel>,
}

impl CoordinodeClient {
    // ── Constructors ──────────────────────────────────────────────────────────

    /// Connect to `endpoint` with default settings (no source tracking).
    ///
    /// Equivalent to `CoordinodeClient::builder(endpoint).build().await`.
    pub async fn connect(endpoint: impl Into<String>) -> Result<Self, ClientError> {
        CoordinodeClientBuilder::new(endpoint).build().await
    }

    /// Return a builder to configure the client before connecting.
    pub fn builder(endpoint: impl Into<String>) -> CoordinodeClientBuilder {
        CoordinodeClientBuilder::new(endpoint)
    }

    /// Internal: connect using a fully-built [`ClientConfig`].
    pub(crate) async fn connect_with_config(config: ClientConfig) -> Result<Self, ClientError> {
        let channel = tonic::transport::Channel::from_shared(config.endpoint.clone())
            .map_err(|e| ClientError::InvalidEndpoint(e.to_string()))?
            .connect()
            .await?;

        let cypher = CypherServiceClient::new(channel);

        Ok(Self { config, cypher })
    }

    // ── Cypher ────────────────────────────────────────────────────────────────

    /// Execute a Cypher query with no parameters.
    ///
    /// When `debug_source_tracking` is enabled, the caller's source location
    /// is attached to the request automatically via `#[track_caller]`.
    ///
    /// # Note on `#[track_caller]` and async
    ///
    /// Rust does not yet stabilise `#[track_caller]` on `async fn` (rust-lang/rust#110011).
    /// This method is therefore a synchronous `#[track_caller]` wrapper that captures
    /// `Location::caller()` before delegating to the async implementation. From the
    /// caller's perspective the API is unchanged: `client.execute_cypher(...).await`.
    #[track_caller]
    pub fn execute_cypher(
        &mut self,
        query: impl Into<String>,
    ) -> impl Future<Output = Result<Vec<Row>, ClientError>> + '_ {
        // Location is captured HERE — in the synchronous, #[track_caller] wrapper —
        // so it points to the user's call site, not to driver internals.
        let location = if self.config.debug_source_tracking {
            Some(Location::caller())
        } else {
            None
        };
        self.execute_cypher_inner(query.into(), HashMap::new(), location)
    }

    /// Execute a Cypher query with named parameters.
    ///
    /// ```no_run
    /// # tokio_test::block_on(async {
    /// # use std::collections::HashMap;
    /// # use coordinode_client::{CoordinodeClient, Value};
    /// # let mut client = CoordinodeClient::connect("http://localhost:7080").await.unwrap();
    /// let mut params = HashMap::new();
    /// params.insert("id".to_string(), Value::Int(42));
    ///
    /// let rows = client.execute_cypher_with_params(
    ///     "MATCH (u:User {id: $id}) RETURN u.name",
    ///     params,
    /// ).await.unwrap();
    /// # })
    /// ```
    #[track_caller]
    pub fn execute_cypher_with_params(
        &mut self,
        query: impl Into<String>,
        params: HashMap<String, Value>,
    ) -> impl Future<Output = Result<Vec<Row>, ClientError>> + '_ {
        let location = if self.config.debug_source_tracking {
            Some(Location::caller())
        } else {
            None
        };
        self.execute_cypher_inner(query.into(), params, location)
    }

    /// Execute a read query with an explicit [`ReadPreference`].
    ///
    /// [`execute_cypher`] and [`execute_cypher_with_params`] always
    /// route to the Raft leader; this method lets a connection to a
    /// follower serve reads ([`ReadPreference::Secondary`] /
    /// [`SecondaryPreferred`] / [`Nearest`]) for read scale-out.
    /// Follower reads observe that follower's applied state — use
    /// [`execute_causal_read`] when the read must observe a specific
    /// prior write.
    ///
    /// [`execute_cypher`]: CoordinodeClient::execute_cypher
    /// [`execute_cypher_with_params`]: CoordinodeClient::execute_cypher_with_params
    /// [`execute_causal_read`]: CoordinodeClient::execute_causal_read
    /// [`SecondaryPreferred`]: ReadPreference::SecondaryPreferred
    /// [`Nearest`]: ReadPreference::Nearest
    #[track_caller]
    pub fn execute_cypher_with_read_preference(
        &mut self,
        query: impl Into<String>,
        params: HashMap<String, Value>,
        read_preference: ReadPreference,
    ) -> impl Future<Output = Result<Vec<Row>, ClientError>> + '_ {
        let location = if self.config.debug_source_tracking {
            Some(Location::caller())
        } else {
            None
        };
        let query = query.into();
        async move {
            let (rows, _applied_index) = self
                .execute_request(
                    query,
                    params,
                    read_preference.to_proto(),
                    None,
                    None,
                    location,
                )
                .await?;
            Ok(rows)
        }
    }

    // ── Causal consistency ────────────────────────────────────────────────────

    /// Execute a write with **majority durability**, returning a causal token.
    ///
    /// The write is acknowledged only after a quorum of replicas has applied
    /// it to their Raft log. The returned [`CausalToken`] wraps the committed
    /// log index and can be passed to [`execute_causal_read`] to enforce
    /// read-your-writes ordering — even when the read is served by a follower.
    ///
    /// **Standalone / embedded mode:** the token is always `0` (the server
    /// operates without Raft). Passing it to a causal read has no fence effect.
    ///
    /// # Errors
    ///
    /// Returns `ClientError::Grpc` if the server rejects the request (e.g. the
    /// node is not the Raft leader, or `read_concern.after_index` is set with
    /// a non-majority write concern).
    ///
    /// [`execute_causal_read`]: CoordinodeClient::execute_causal_read
    #[track_caller]
    pub fn execute_causal_write(
        &mut self,
        query: impl Into<String>,
    ) -> impl Future<Output = Result<(Vec<Row>, CausalToken), ClientError>> + '_ {
        let location = if self.config.debug_source_tracking {
            Some(Location::caller())
        } else {
            None
        };
        self.execute_causal_write_inner(query.into(), HashMap::new(), location)
    }

    /// Execute a write with **majority durability** and named parameters.
    ///
    /// Identical to [`execute_causal_write`] but accepts query parameters.
    ///
    /// [`execute_causal_write`]: CoordinodeClient::execute_causal_write
    #[track_caller]
    pub fn execute_causal_write_with_params(
        &mut self,
        query: impl Into<String>,
        params: HashMap<String, Value>,
    ) -> impl Future<Output = Result<(Vec<Row>, CausalToken), ClientError>> + '_ {
        let location = if self.config.debug_source_tracking {
            Some(Location::caller())
        } else {
            None
        };
        self.execute_causal_write_inner(query.into(), params, location)
    }

    /// Execute a read that is guaranteed to observe the write identified by
    /// `after`.
    ///
    /// The serving node waits until its applied log index is ≥ `after.as_u64()`
    /// before executing the read. This guarantees **read-your-writes** and
    /// **monotonic reads** when the write was issued with
    /// [`execute_causal_write`].
    ///
    /// Use `ReadPreference::SECONDARY_PREFERRED` in combination with this
    /// method to scale out reads while preserving causal ordering.
    ///
    /// **Standalone / embedded mode:** the fence has no effect (the server
    /// returns immediately).
    ///
    /// [`execute_causal_write`]: CoordinodeClient::execute_causal_write
    #[track_caller]
    pub fn execute_causal_read(
        &mut self,
        query: impl Into<String>,
        after: CausalToken,
    ) -> impl Future<Output = Result<Vec<Row>, ClientError>> + '_ {
        let location = if self.config.debug_source_tracking {
            Some(Location::caller())
        } else {
            None
        };
        self.execute_causal_read_inner(query.into(), HashMap::new(), after, location)
    }

    /// Execute a causal read with named parameters.
    ///
    /// Identical to [`execute_causal_read`] but accepts query parameters.
    ///
    /// [`execute_causal_read`]: CoordinodeClient::execute_causal_read
    #[track_caller]
    pub fn execute_causal_read_with_params(
        &mut self,
        query: impl Into<String>,
        params: HashMap<String, Value>,
        after: CausalToken,
    ) -> impl Future<Output = Result<Vec<Row>, ClientError>> + '_ {
        let location = if self.config.debug_source_tracking {
            Some(Location::caller())
        } else {
            None
        };
        self.execute_causal_read_inner(query.into(), params, after, location)
    }

    // ── Config access ─────────────────────────────────────────────────────────

    /// Returns `true` when source location tracking is enabled.
    pub fn source_tracking_enabled(&self) -> bool {
        self.config.debug_source_tracking
    }

    // ── Internals ─────────────────────────────────────────────────────────────

    async fn execute_cypher_inner(
        &mut self,
        query: String,
        params: HashMap<String, Value>,
        location: Option<&'static Location<'static>>,
    ) -> Result<Vec<Row>, ClientError> {
        let (rows, _applied_index) = self
            .execute_request(
                query, params, 0,    // read_preference = PRIMARY
                None, // read_concern = LOCAL (default)
                None, // write_concern = W1 (default)
                location,
            )
            .await?;
        Ok(rows)
    }

    async fn execute_causal_write_inner(
        &mut self,
        query: String,
        params: HashMap<String, Value>,
        location: Option<&'static Location<'static>>,
    ) -> Result<(Vec<Row>, CausalToken), ClientError> {
        let write_concern = Some(WriteConcern {
            level: WriteConcernLevel::Majority as i32,
            journal: false,
            timeout_ms: 0,
        });
        let (rows, applied_index) = self
            .execute_request(query, params, 0, None, write_concern, location)
            .await?;
        Ok((rows, CausalToken(applied_index)))
    }

    async fn execute_causal_read_inner(
        &mut self,
        query: String,
        params: HashMap<String, Value>,
        after: CausalToken,
        location: Option<&'static Location<'static>>,
    ) -> Result<Vec<Row>, ClientError> {
        let read_concern = Some(ReadConcern {
            level: ReadConcernLevel::Majority as i32,
            after_index: after.as_u64(),
            at_timestamp: 0, // causal read uses fence, not snapshot pin
        });
        let (rows, _applied_index) = self
            .execute_request(query, params, 0, read_concern, None, location)
            .await?;
        Ok(rows)
    }

    /// Low-level request executor shared by all public methods.
    ///
    /// Returns the decoded rows **and** the `applied_index` from `QueryStats`
    /// so causal methods can wrap it in a [`CausalToken`].
    async fn execute_request(
        &mut self,
        query: String,
        params: HashMap<String, Value>,
        read_preference: i32,
        read_concern: Option<ReadConcern>,
        write_concern: Option<WriteConcern>,
        location: Option<&'static Location<'static>>,
    ) -> Result<(Vec<Row>, u64), ClientError> {
        let proto_params = params
            .into_iter()
            .map(|(k, v)| (k, value::to_proto(v)))
            .collect();

        let mut request = tonic::Request::new(ExecuteCypherRequest {
            query,
            parameters: proto_params,
            read_preference,
            read_concern,
            write_concern,
            // Auto-commit: this convenience wrapper runs each statement on its
            // own. Interactive transactions use the BeginTransaction RPC and
            // set transaction_id on the request directly.
            transaction_id: 0,
        });

        if let Some(loc) = location {
            source::inject_grpc_metadata(request.metadata_mut(), loc, &self.config);
        }

        let response = self.cypher.execute_cypher(request).await?;
        let body = response.into_inner();

        let applied_index = body.stats.as_ref().map_or(0, |s| s.applied_index);

        let columns = body.columns;
        let rows = body
            .rows
            .into_iter()
            .map(|row| {
                columns
                    .iter()
                    .zip(row.values)
                    .map(|(col, pv)| (col.clone(), value::from_proto(pv)))
                    .collect::<Row>()
            })
            .collect();

        Ok((rows, applied_index))
    }
}

// ── Unit tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests;
